# Serverless SNS
service: pact-events

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
        - "dynamodb:*"
  environment:
    TOPIC_ARN: { "Fn::Join":  ["", ["arn:aws:sns:us-east-1:", { "Ref": "AWS::AccountId" }, ":pact-events"] ] }
    MAGIC_KEYWORD: "#AWSSummit"
    # NOTE: These must be present in your shell!
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
  events:
    - schedule: rate(1 minute)

package:
  individually: true
  exclude:
    - "node_modules/@pact-foundation/**"
    - "node_modules/aws-sdk/**"

functions:
  provider:
    handler: provider/index.handler
  consumer:
    handler: consumer/index.handler
    events:
      - sns: pact-events

resources:
  Resources:
    checkpointTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: checkpoint
        AttributeDefinitions:
          - AttributeName: Type
            AttributeType: S
        KeySchema:
          - AttributeName: Type
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1